project:
  type: website
  output-dir: docs

website:
  title: "Gender, assessment, and performance in introductory biology"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: variables.qmd
        text: Variables
      - href: results.qmd
        text: Results
      - href: preceptor-table.qmd
        text: Model
      - href: study.qmd
        text: Study Context

format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [cosmo, styles.scss]
    toc: true
    code-fold: true
    embed-resources: true
    page-layout: full

execute:
  echo: false
  warning: false
  message: false
